# Generated by Django 4.2.11 on 2024-04-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_maintickets_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintickets',
            name='attachment',
        ),
        migrations.AddField(
            model_name='maintickets',
            name='file_content',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
