# Generated by Django 4.2.11 on 2024-04-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_maintickets_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintickets',
            name='file_mime_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maintickets',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
